# ElytraLimiter
# V1.0

# -- Options section
# Limit of elytra that a player can have.
limit-per-player: 5

# The list of world to check when an elytra is taken from an item frame.
# Note : only include end world(s) to increase their elytra collected
#        amount only via natural loot way.
worlds-to-check:
  - world_the_end
  - other_world_if_needed

# -- Messages section
# Accept '&' color code format.
no-perm: "&c&lYourServer &8» &cYou don't have permission to do that."
not-a-whole-number: "&c&lYourServer &8» Argument was not an whole number."
limit-reach: "&c&lYourServer &8» &cYou have reached the limit of elytra possible."
amount-of-elytra: "You've collected %nbElytra out of %limit allowed."